
# Site settings
title: My page alberth
email:
description:  # this means to ignore newlines until "baseurl:" 
url: https://yapitalapaz.github.io/

# User setting
owner:
email: "maikeru.bash@gmail.com"
facebook_username: michael apaza
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
gems: []

markdown: 
# toc_levels: 1..2
